<?php

namespace StockBundle\Repository;

/**
 * PortfolioQuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioQuoteRepository extends \Doctrine\ORM\EntityRepository
{
}
