<?php

namespace StockBundle\Repository;

/**
 * QuoteCharRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteCharRepository extends \Doctrine\ORM\EntityRepository
{
}
