stock_portfolio:
    resource: "@StockBundle/Resources/config/routing/portfolio.yml"
    prefix:   /portfolio

stock_homepage:
    path:     /
    defaults: { _controller: StockBundle:Default:index }
